export const ANCHORS = {
  ABOUT_EVENT: "#about-event",
  AFTER_PARTY: "#after-party",
  AUCTION: "#auction",
  BENEFITS: "#benefits",
  CONTACTS: "#contacts",
  EXHIBIT: "#exhibit",
  EXHIBITION_AREA: "#exhibition-area",
  FORUM: "#forum",
  INSPIRATION: "#inspiration",
  JOIN: "#join",
  LECTURE: "#lecture",
  PARTNERS: "#partners",
  VIDEO_PROJECT: "#video-project",
};
